name: Code format

on:
  pull_request:

jobs:
  lint:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "check format"
        run: |
          make fmt
