name: Players Lint

on:
  pull_request:
    paths-ignore:
      - 'wake/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install-dependencies
        run: |
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
          sudo apt-get install libwayland-dev libxkbcommon-dev
      - name: "check lint with clippy"
        run: |
          make lint-players
